### ISSUE TITLE
FirebaseAuth Session Storage

### ISSUE THREAD

**Issue by BK1031** [Team3256/myWB-web#1]
Yeahh, firebase is being really stupid with flutter web.

**TODO**
- Store Firebase UID in either local storage or cookies to save login state
- Use this stored id for all api operations from now on
- Should make load times a lot better, and get rid of almost all the uid null errors

**Comment by Saamstep** [comment]
WeirdChamp

**Comment by Anon10W1z** [comment]
F

**Comment by Saamstep** [comment]
> F

@Anon10W1z 😮 HUGE FAN

**Comment by BK1031** [comment]
used LocalStorage from the dart:html plugin.
